# Document  $Id$
# Summary   Makefile includes for the chemical-mime-data project.
#
# Copyright (C) 2007 by Daniel Leidert <daniel.leidert@wgdd.de>.
#
# This file is free software. The copyright owner gives unlimited
# permission to copy, distribute and modify it.

GNOME_VFS_MIME_XML_CUSTOM = \
	<gnome-vfs-mime xmlns:xi="http://www.w3.org/2001/XInclude" > \
		<xi:include href="$(GNOME_VFS_MIME_DATA_DB)" parse="text" encoding="utf-8"/> \
	</gnome-vfs-mime>


MIME_SUPPORT_MIME_TYPES_XML_CUSTOM = \
	<mime-types-mime xmlns:xi="http://www.w3.org/2001/XInclude" > \
		<xi:include href="$(MIME_SUPPORT_MIME_TYPES_DATA_DB)" parse="text" encoding="utf-8"/> \
	</mime-types-mime>

